#!/bin/bash

# This script is expected to be called with the GIT_DIR directory set to the
# directory of the component which have been changed.
# It is called by each component to launch post-receive hook.

SCRIPT_DIR="$(dirname "$(readlink -e "$0")")"
. "$SCRIPT_DIR/helpers"

hook_files="$(ls "$SCRIPT_DIR/"*-hook)"
#local_hook_files="$

echo "Launch generic-post-receive..." | divert_to_log

# We loop until there is no more input, because another push may happen while
# we’re executing.
while read oldrev newrev refname; do
    for hook_file in $hook_files; do
        ## we launch all functions in a subshell to avoid as much as possible
        ## cross-effects.
        export oldrev newrev refname
        launch_hook "$hook_file" post-receive_ref
    done
done

for hook_file in $hook_files; do
    launch_hook "$hook_file" post-receive_post
done


test -d "$tmpdir" && rm -rf "$tmpdir"
